"""initial schema

Revision ID: 21e74b7be35a
Revises: 
Create Date: 2026-05-01 15:43:40.532004

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_initial_schema'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('current_date', sa.Date(), nullable=False),
    sa.Column('player_polity_name', sa.String(length=200), nullable=False),
    sa.Column('lore_md', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('consolidated_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('key_events', sa.JSON(), nullable=False),
    sa.Column('state_changes_summary', sa.Text(), nullable=False),
    sa.Column('emerging_tensions', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diplomatic_log_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('counterparty_polity', sa.String(length=200), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('from_polity', sa.String(length=200), nullable=False),
    sa.Column('to_polity', sa.String(length=200), nullable=False),
    sa.Column('message_in', sa.Text(), nullable=True),
    sa.Column('message_out', sa.Text(), nullable=True),
    sa.Column('proposed_deltas', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diplomatic_relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('polity_a', sa.String(length=200), nullable=False),
    sa.Column('polity_b', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('opinion_a_to_b', sa.Integer(), nullable=False),
    sa.Column('opinion_b_to_a', sa.Integer(), nullable=False),
    sa.Column('treaties', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'polity_a', 'polity_b', name='uq_diplomatic_relations_campaign_pair')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=40), nullable=False),
    sa.Column('caused_by', sa.String(length=40), nullable=False),
    sa.Column('affected_polities', sa.JSON(), nullable=False),
    sa.Column('affected_regions', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('ix_events_campaign_date', ['campaign_id', 'date'], unique=False)

    op.create_table('pending_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('submitted_on', sa.Date(), nullable=False),
    sa.Column('target_polities', sa.JSON(), nullable=False),
    sa.Column('target_regions', sa.JSON(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('polities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('government_type', sa.String(length=400), nullable=False),
    sa.Column('leader', sa.String(length=200), nullable=False),
    sa.Column('capital_region_name', sa.String(length=200), nullable=False),
    sa.Column('stability', sa.Integer(), nullable=False),
    sa.Column('war_support', sa.Integer(), nullable=False),
    sa.Column('treasury', sa.Integer(), nullable=False),
    sa.Column('manpower', sa.Integer(), nullable=False),
    sa.Column('political_power', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'name', name='uq_polities_campaign_name')
    )
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('owner_polity_name', sa.String(length=200), nullable=True),
    sa.Column('population_estimate_thousands', sa.Integer(), nullable=False),
    sa.Column('economic_profile', sa.Text(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'name', name='uq_regions_campaign_name')
    )
    op.create_table('scheduled_event_fires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=200), nullable=False),
    sa.Column('fired_at_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'event_id', name='uq_scheduled_event_fires_campaign_event')
    )
    op.create_table('battalions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('polity_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('location_region_name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['polity_id'], ['polities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doctrines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('polity_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=400), nullable=False),
    sa.Column('ordering', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['polity_id'], ['polities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('internal_tensions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('polity_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=400), nullable=False),
    sa.Column('ordering', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['polity_id'], ['polities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('internal_tensions')
    op.drop_table('doctrines')
    op.drop_table('battalions')
    op.drop_table('scheduled_event_fires')
    op.drop_table('regions')
    op.drop_table('polities')
    op.drop_table('pending_actions')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_campaign_date')

    op.drop_table('events')
    op.drop_table('diplomatic_relations')
    op.drop_table('diplomatic_log_entries')
    op.drop_table('consolidated_summaries')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
